version: '3'
services:
  streamlit-massql-post-mn:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamlit-massql-post-mn
    volumes:
      - ./logs:/app/logs:rw
      - ./temp:/app/temp_mgf:rw
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    logging:
      driver: json-file
      options:
        max-size: "10m"      # Maximum size of a single log file
        max-file: "3"        # Maximum number of log files to keep (rotates after 3 files)
    deploy:
      resources:
        limits:
          memory: 8000M
    environment:
      VIRTUAL_HOST: massqlpostmn.gnps2.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: massqlpostmn.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com

networks:
  nginx-net:
    external:
      name: nginx-net